### PR TITLE
Fix link to source code of AuthOptions

### PR DESCRIPTION
**Pull request by friedger**
This PR
* replace the current link to the source code of `AuthOptions` from the connect repo to the ux repo.
* updates the optional flags in the properties table of `AuthOptions`

### CODE REVIEW

**Review by agraebe — APPROVED** [review]
thanks @friedger. cc @hstove

**Review by agraebe — APPROVED** [review]
thanks @friedger!

**Comment by hstove** [comment]
Thank you for fixing the link!

RE: the changes to AuthOptions. I know those fields are technically not required as per the Typescript definition, but I would lean more towards making them mandatory. You really need the `finished` and `redirectTo` options to fully implement authentication. My only hesitation to changing the TS definition is that it would be a breaking change. I definitely do not want our docs to indicate that these fields are optional, because you need them to implement auth.

**Review by hstove — APPROVED** [review]

**Comment by hstove** [comment]
LGTM! Thanks for updating the PR @friedger .

**Comment by hstove** [comment]
I'm unable to merge this. Someone with Vercel access can authorize the deploy, which should make all status checks pass. Or, someone with admin rights in this repo (maybe @agraebe ?) can merge.

**Comment by aulneau** [comment]
Merged!

**Pull request merged**
