### PR TITLE
Update tutorials for krypton miners

### PR DESCRIPTION
**Pull request by lgalabru**

### CODE REVIEW

**Review by CharlieC3 — APPROVED** [review]
LGTM :shipit:

**Comment by CharlieC3** [comment]
We might need to change the sidecar URLs to remove the `-latest` part if we're going to get rid of one of the sidecar deployments. Will need @zone117x to confirm if the two sidecar deployments is still needed.

**Comment by zone117x** [comment]
Two deployments is not needed. The URLs should be updated 👍

**Review by agraebe — APPROVED** [review]

**Comment by wileyj** [comment]
I think we can further simplify the DNS names here

**Review by CharlieC3 — APPROVED** [review]
@wileyj Good catch on the `xyz` -> `org`!
:shipit: LGTM

**Comment by lgalabru** [comment]
Thank you @wileyj!

**Pull request merged**
