### PR TITLE
feat: alphabetize functions and keywords lists #744

### PR DESCRIPTION
**Pull request by friedger**
## Description

This PR sorts the functions and keywords list by name, the content is sorted in the same way.

For details refer to issue #744 

**Before**
Screenshot from 2020-11-04 22-53-24

**After**
Screenshot from 2020-11-04 22-53-47

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information
No

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [x] Changelog is updated
- [x] Tag 1 of @agraebe

### CODE REVIEW

**Comment by friedger** [comment]
A screenshot of the keyword list and its content

Screenshot from 2020-11-04 22-58-28

**Review by agraebe — APPROVED** [review]
🙏

**Comment by agraebe** [comment]
@aulneau if you have nothing to add, I'll merge this today. thanks!

**Comment by agraebe** [comment]
@friedger with the pages now split up into 4 different ones - does this PR need an update or not?

**Comment by agraebe** [comment]
looks like this is not impacted by the split of the pages. merging now

**Pull request merged**
