### PR TITLE
feat: proposal for an interactive tour of Clarity

### PR DESCRIPTION
**Pull request by lgalabru**
## Description

This PR is a proposal for introducing an interactive tour of Clarity, based on Jupyter notebooks. 

Right now, the notebooks are hosted on a free service, so the initialization is pretty slow, but we can probably address this problem by throwing some money at it.

Concerning the look and feel, Jupyter notebooks are by default rudimentary and not very appealing, but @aulneau and I talked a few months ago, and I think there are ways to tweak this.  

Concerning the content, it's still very much draft / work in progress. If we think that this approach make sense, then we can iterate on this and ship it.

### CODE REVIEW

**Comment by whoabuddy** [comment]
Would this be something we can pair with https://clarity.tools/ rather than Jupyter?

**Comment by aulneau** [comment]
@whoabuddy I am currently working on an inline clarity repl implementation :)

**Comment by agraebe** [comment]
what should be the next step here?

**Comment by lgalabru** [comment]
@agraebe I'm not sure. If you're in the process of "marie kondo"-ing the PRs in that repo, then we can open an issue, close that PR, and re-evaluate once we have bandwidth for the notebooks?

**Comment by lgalabru** [comment]
> Would this be something we can pair with https://clarity.tools/ rather than Jupyter?

Probably. Clarity.tools not being source, it's hard to know what does the underlying format looks like.

**Comment by agraebe** [comment]
> in the process of "marie kondo"-ing the PRs

haha, I've never heard that name but I heard of the book. yeah, let's do what you suggested!

**Pull request closed without merging**
