### PR TITLE
feat: full-width docs

### PR DESCRIPTION
**Pull request by agraebe**
Fixes blockstack/docs#947

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
Big improvement, thanks @agraebe

**Comment by aulneau** [comment]
I'm generally in favor of this change, but I think we should hear from @jasperjansz before merging this in. Additionally, I wonder if we should have the TOC on the right, all the way to the right?

**Comment by agraebe** [comment]
> I'm generally in favor of this change, but I think we should hear from @jasperjansz before merging this in. Additionally, I wonder if we should have the TOC on the right, all the way to the right?

Agreed, been waiting to hear from @jasperjansz but couldn't get anyone's eyes on this for a week. I had a version of this on the very right and it didn't look great - felt like it was disconnected from the content. I looked at Stripe docs and they seem to have the same layout (which shouldn't be a strong argument, but it's _a signal_)

**Comment by jasperjansz** [comment]
Im fine with this change.

If you want to make it read easier, you can decrease the width of the center column so you'll have less words per line. Currently you're close to 130 while 80-90 is optimal for reading for prolonged periods.

**Comment by agraebe** [comment]
please have another look at the deployed version. I set the width to 860px to optimize the reading experience as per @jasperjansz's advice

**Pull request merged**
