### PR TITLE
fix: update the Stacks Docs logo per Ginny

### PR DESCRIPTION
**Pull request by pgray-hiro**
## Description

According to @eugeniadigon the font for the logo we are using on the documentation site is wrong, she provided a correct SVG that builds the Stacks logo with the Docs substring.

## Checklist

- [x] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] New links to files and images were verified
- [x] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [x] Clear code samples were provided
- [x] People were tagged for review

### CODE REVIEW

**Review by aulneau — APPROVED** [review]

**Comment by eugeniadigon** [comment]
The logo needs to be slightly smaller, keeping the same height as the current logo

Current logo is 18.281 height
Updated logo is 19.938 height

Thanks

**Comment by pgray-hiro** [comment]
@eugeniadigon I was trying to bring this logo size in line with stacks.co which has a 20px height - WDYT?

**Comment by eugeniadigon** [comment]
> @eugeniadigon I was trying to bring this logo size in line with stacks.co which has a 20px height - WDYT?

Good thinking, but in this case it's not in the same position, so doesn't really look in line with stacks.co, so please do 18.281 height
Thanks!

**Comment by aulneau** [comment]
Decimal units on the web are not really supported well, I'd suggest 18px

**Comment by pgray-hiro** [comment]
Adjusting the width to `156px` gets us a height of `18.3px` - close enough?

**Comment by eugeniadigon** [comment]
> Decimal units on the web are not really supported well, I'd suggest 18px

I understand, I just want to keep it same as what it is right now on the site, which is: 

Screenshot 2021-05-14 at 15 27 22

**Pull request merged**
